# Generated by Django 3.2.3 on 2021-06-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
