# Generated by Django 3.2.4 on 2021-06-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_kitchen_working_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='working_days',
        ),
    ]
