# Generated by Django 3.2.4 on 2021-06-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_remove_kitchen_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='working_days',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
