# Generated by Django 3.2.4 on 2021-06-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20210626_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
