# Generated by Django 3.2.4 on 2021-06-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_kitchen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchen'),
        ),
    ]
