# Generated by Django 3.2.3 on 2021-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_food_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
