# Generated by Django 3.2.3 on 2021-06-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0009_alter_kitchen_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('question_1', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('question_2', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('is_provider', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
