# Generated by Django 3.2.3 on 2021-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_eater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eater',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='eater',
            name='last_name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
